services:
  - type: web
    name: realnex-chatbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: REDIS_HOST
        value: redis-11362.c265.us-east-1-2.ec2.redns.redis-cloud.com
      - key: REDIS_PORT
        value: 11362
      - key: REDIS_USERNAME
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_CA_PATH
        value: certs/redis_ca.pem
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: REALNEX_API_BASE
        value: https://sync.realnex.com/api/v1
      - key: MAILCHIMP_SERVER_PREFIX
        value: us1
      - key: GOOGLE_API_KEY
        sync: false
